"use client";
import React, { useState, useEffect } from "react";
import { useParams, useRouter } from "next/navigation";
import {
  ArrowRight,
  CheckCircle,
  Users,
  Brain,
  Heart,
  MessageCircle,
  TrendingUp,
  Shield,
  Star,
  ChevronDown,
  ChevronUp,
  Play,
  BarChart3,
  Target,
  Lock,
  Award,
  Clock,
  RefreshCw,
} from "lucide-react";
import Image from "next/image";

export default function Sales() {
  const { typeCode } = useParams();
  const router = useRouter();
  const [activeNav, setActiveNav] = useState("home");
  const [expandedFAQ, setExpandedFAQ] = useState(null);
  const [email, setEmail] = useState("");
  const [isEmailSubmitted, setIsEmailSubmitted] = useState(false);

  useEffect(() => {
    if (typeCode) {
      localStorage.setItem("userTypeCode", typeCode);
    }

    const handleScroll = () => {
      const sections = ["home", "how-it-works", "whats-inside", "faq", "buy-now"];
      const currentSection = sections.find((section) => {
        const element = document.getElementById(section);
        if (element) {
          const rect = element.getBoundingClientRect();
          return rect.top <= 100 && rect.bottom >= 100;
        }
        return false;
      });
      if (currentSection) setActiveNav(currentSection);

      const elements = document.querySelectorAll(".section-header");
      elements.forEach((el) => {
        const rect = el.getBoundingClientRect();
        if (rect.top <= window.innerHeight * 0.8) {
          el.classList.add("animate");
        }
      });
    };

    window.addEventListener("scroll", handleScroll);
    handleScroll();
    return () => window.removeEventListener("scroll", handleScroll);
  }, [typeCode]);

  const scrollToSection = (sectionId) => {
    const element = document.getElementById(sectionId);
    if (element) element.scrollIntoView({ behavior: "smooth" });
  };

  const handleEmailSubmit = (e) => {
    e.preventDefault();
    setIsEmailSubmitted(true);
    setTimeout(() => setIsEmailSubmitted(false), 3000);
  };

  const toggleFAQ = (index) => {
    setExpandedFAQ(expandedFAQ === index ? null : index);
  };

  const handlePurchase = () => {
    router.push(`/report/${typeCode}/couples/signup`);
  };

  const faqs = [
    {
      question: "Is CSM scientifically legit, or just another buzzword quiz?",
      answer:
        "The Cognitive Spectrum Model is built on established psychological research, combining elements from cognitive science, behavioral psychology, and systems theory. Unlike pop psychology quizzes, CSM uses psychometrically validated questions and has been tested with over 10,000 individuals to ensure reliable, actionable insights.",
    },
    {
      question: "What is the Cognitive Spectrum Model (CSM), and why should I care?",
      answer:
        "CSM maps how your mind processes information, makes decisions, and approaches life's domains. Instead of putting you in a box, it shows you as a spectrum across multiple cognitive dimensions. This helps couples understand not just what they do differently, but why,leading to deeper empathy and more effective communication.",
    },
    {
      question: "How is CSM different from MBTI, Enneagram, or Big Five?",
      answer:
        "While those systems categorize personality, CSM focuses on cognitive processing patterns and how they apply to real-life situations. It's more actionable for couples because it shows how your thinking styles interact across specific life domains like finances, parenting, and career decisions.",
    },
    {
      question: "Why should I trust CSM over free online quizzes?",
      answer:
        "Free quizzes often lack scientific rigor and provide generic results. CSM uses advanced algorithms to analyze your responses across multiple dimensions, providing personalized insights specific to your relationship dynamic. Our reports are generated by licensed relationship experts, not automated generic templates.",
    },
    {
      question: "Can CSM really 'read' my relationship like a mind reader?",
      answer:
        "CSM doesn't predict the future, but it reveals patterns in how you and your partner approach life's challenges. Think of it as a GPS for your relationship,it shows you where you are now and suggests the best routes forward based on your unique dynamic.",
    },
    {
      question: "How does the free assessment work?",
      answer:
        "The free assessment takes 10-15 minutes and identifies your individual cognitive archetype. You'll get immediate insights about your processing style. To unlock the full couple's report, you'll invite your partner to take their assessment, and our system generates a comprehensive analysis of your combined dynamic.",
    },
    {
      question: "Do I need my partner to start?",
      answer:
        "No! Start with the free individual assessment to discover your own archetype. You can invite your partner later to unlock the full couple's report. Many people find their individual insights so valuable that their partner becomes curious to participate.",
    },
    {
      question: "Can CSM predict if we're soulmates or just spot potential issues?",
      answer:
        "CSM focuses on compatibility and growth opportunities rather than making destiny predictions. It shows you where you naturally complement each other and where you might face challenges, giving you tools to navigate both successfully.",
    },
    {
      question: "How quickly will I get my results?",
      answer:
        "Individual results are instant after completing the free assessment. The full couple's report is generated within 24 hours after both partners complete their assessments. You'll receive an email notification when it's ready.",
    },
    {
      question: "Is CSM therapy or coaching?",
      answer:
        "CSM is an assessment tool that provides insights and recommendations. While it includes a complimentary coaching session, it's not a substitute for therapy. Think of it as a roadmap that can enhance any relationship work you're already doing.",
    },
    {
      question: "What if my partner doesn't want to participate?",
      answer:
        "Start with your free individual assessment! You'll gain valuable self-insights, and many partners become interested once they see the quality of results. The individual report alone provides significant value for personal growth and relationship awareness.",
    },
    {
      question: "What's the refund policy?",
      answer:
        "We offer a 14-day satisfaction guarantee, no questions asked. If you're not completely satisfied with your couple's insights report, we'll provide a full refund. We're confident in the value CSM provides to couples.",
    },
  ];

  return (
    <div className="min-h-screen">
      {/* Sticky Header */}
      <header className="fixed top-0 w-full left-0 right-0 z-50 bg-[var(--dashboard)]/90 backdrop-blur-lg border-b border-[var(--border)]">
        <nav className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <Image
                src="/imagens/logo_transparent_svg.svg"
                alt="CSM Dynamics Logo"
                width={32}
                height={32}
                className="h-8 w-8"
              />
              <div className="flex items-center space-x-1">
                <h1 className="text-xl font-bold text-[var(--primary)]">CSM</h1>
                <h1 className="text-xl font-light text-[var(--text-primary)]">Dynamics</h1>
              </div>
            </div>
            <div className="hidden md:flex space-x-8">
              {[
                { id: "home", label: "Home" },
                { id: "how-it-works", label: "How It Works" },
                { id: "whats-inside", label: "What's Inside" },
                { id: "faq", label: "FAQ" },
                { id: "buy-now", label: "Buy Now" },
              ].map((item) => (
                <button
                  key={item.id}
                  onClick={() => scrollToSection(item.id)}
                  className={`transition-colors ${
                    activeNav === item.id
                      ? "text-[var(--accent)]"
                      : "text-[var(--text-secondary)] hover:text-[var(--text-primary)]"
                  }`}
                >
                  {item.label}
                </button>
              ))}
            </div>
            <button
              onClick={() => scrollToSection("buy-now")}
              className="btn-primary px-6 py-2 rounded-lg font-semibold"
            >
              Get Started
            </button>
          </div>
        </nav>
      </header>

      {/* Hero Section */}
      <section id="home" className="pt-24 pb-16 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="grid lg:grid-cols-2 gap-12 items-center">
            <div className="section-header">
              <div className="bg-[var(--accent)]/20 text-[var(--accent)] px-4 py-2 rounded-full inline-flex items-center mb-6">
                <Star className="h-4 w-4 mr-2" />
                Limited-time: Get 10% off with code FUTURE10
              </div>
              <h1 className="text-5xl md:text-6xl font-bold mb-6 leading-tight">
                Chart the Future of Your
                <span className="text-[var(--accent)]"> Relationship</span>
              </h1>
              <p className="text-xl text-[var(--text-secondary)] mb-8 leading-relaxed">
                The CSM {"Couple's"} Insight Report is a personalized guide to your relationship dynamic, grounded in
                modern psychology. Understand your combined strengths, navigate future challenges, and build a more
                conscious connection.
              </p>
              <div className="space-y-4">
                <button
                  onClick={handlePurchase}
                  className="btn-primary px-8 py-4 rounded-lg font-semibold text-lg inline-flex items-center group"
                >
                  Discover Your Dynamic
                  <ArrowRight className="ml-2 h-5 w-5 group-hover:translate-x-1 transition-transform" />
                </button>
                <p className="text-[var(--text-secondary)] flex items-center">
                  <Play className="h-4 w-4 mr-2 text-[var(--accent)]" />
                  Start with a free personality assessment to unlock your archetype,then invite your partner!
                </p>
              </div>
            </div>
            <div className="relative">
              <div className="relative w-full h-96 bg-gradient-to-br from-[var(--primary)]/20 to-[var(--accent)]/20 rounded-lg overflow-hidden">
                <img
                  src="https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg?auto=compress&cs=tinysrgb&w=800"
                  alt="Happy diverse couple looking thoughtfully into the distance together"
                  className="w-full h-full object-cover"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-[var(--surface)]/60 to-transparent"></div>
                <div className="absolute bottom-6 left-6 right-6">
                  <div className="flex space-x-3">
                    <div className="w-8 h-8 bg-[var(--primary)] rounded-full animate-pulse"></div>
                    <div className="w-8 h-8 bg-[var(--accent)] rounded-full animate-pulse delay-150"></div>
                    <div className="w-8 h-8 bg-[var(--primary)] rounded-full animate-pulse delay-300"></div>
                  </div>
                  <p className="text-sm text-[var(--text-secondary)] mt-2">Cognitive patterns merging into synergy</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* The Opportunity Section */}
      <section className="py-16 px-4 bg-[var(--surface-variant)]">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12 section-header">
            <h2 className="text-4xl font-bold mb-6">
              For Couples Who <span className="text-[var(--accent)]">Build</span>, Not Just Repair
            </h2>
            <p className="text-xl text-[var(--text-secondary)] max-w-3xl mx-auto">
              {`Great relationships aren't just about fixing problems,they're about understanding what lies ahead. The CSM
              report gives you the foresight to navigate life's biggest domains before challenges arise.`}
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 mb-12">
            {[
              {
                icon: Target,
                title: "Plan Your Future",
                desc: "Align your approaches to career, finances, and family life.",
              },
              {
                icon: Heart,
                title: "Deepen Your Connection",
                desc: "Understand each other's core needs for love, joy, and personal space.",
              },
              {
                icon: MessageCircle,
                title: "Communicate with Clarity",
                desc: "Learn the 'why' behind your different communication styles.",
              },
              {
                icon: TrendingUp,
                title: "Grow as a Team",
                desc: "Turn individual strengths into a powerful, shared superpower.",
              },
            ].map((item, index) => (
              <div key={index} className="card-gradient p-6 rounded-lg text-center">
                <item.icon className="h-12 w-12 text-[var(--accent)] mx-auto mb-4" />
                <h3 className="text-lg font-semibold mb-3">{item.title}</h3>
                <p className="text-[var(--text-secondary)] text-sm">{item.desc}</p>
              </div>
            ))}
          </div>

          <div className="text-center">
            <p className="text-[var(--accent)] text-lg mb-6">
              <Users className="h-5 w-5 inline mr-2" />
              {`Join 5,000+ couples who've strengthened their bond with CSM insights`}
            </p>
            <button
              onClick={() => router.push("/csm-assessment")}
              className="btn-primary px-8 py-4 rounded-lg font-semibold text-lg inline-flex items-center"
            >
              Start Your Assessment
              <ArrowRight className="ml-2 h-5 w-5" />
            </button>
          </div>
        </div>
      </section>

      {/* Email Signup Form */}
      <section className="py-16 px-4">
        <div className="container mx-auto max-w-2xl text-center">
          <div className="card-gradient p-8 rounded-lg">
            <h3 className="text-2xl font-bold mb-4">Get Free Relationship Tips</h3>
            <p className="text-[var(--text-secondary)] mb-6">
              {`Sign up for our weekly insights and get 10% off your couple's report`}
            </p>
            {!isEmailSubmitted ? (
              <form onSubmit={handleEmailSubmit} className="flex flex-col sm:flex-row gap-4">
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="Enter your email address"
                  className="flex-1 px-4 py-3 rounded-lg bg-[var(--surface)] border border-[var(--border)] text-[var(--text-primary)] placeholder-[var(--text-secondary)] focus:outline-none focus:border-[var(--accent)] transition-[var(--transition)]"
                  required
                />
                <button type="submit" className="btn-primary px-6 py-3 rounded-lg font-semibold whitespace-nowrap">
                  Get Tips + Discount
                </button>
              </form>
            ) : (
              <div className="flex items-center justify-center text-green-400">
                <CheckCircle className="h-5 w-5 mr-2" />
                Thanks! Check your email for your discount code.
              </div>
            )}
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section id="how-it-works" className="py-16 px-4 bg-[var(--surface-variant)]">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12 section-header">
            <h2 className="text-4xl font-bold mb-6">
              Your Blueprint in <span className="text-[var(--accent)]">Three Simple Steps</span>
            </h2>
          </div>

          <div className="grid lg:grid-cols-3 gap-8 mb-12">
            {[
              {
                step: "1",
                title: "Take Your Assessment",
                desc: "Access your dashboard and invite your partner to take the personality assessment.",
                icon: Users,
              },
              {
                step: "2",
                title: "Get Your Report",
                desc: "The full Couple's Insight Report is generated by our algorithm.",
                icon: BarChart3,
              },
              {
                step: "3",
                title: "Transform Your Relationship",
                desc: "Use your report to have deeper conversations and make more intentional decisions together.",
                icon: Heart,
              },
            ].map((item, index) => (
              <div key={index} className="text-center">
                <div className="relative mb-6">
                  <div className="w-20 h-20 bg-[var(--primary)] rounded-full flex items-center justify-center mx-auto mb-4">
                    <item.icon className="h-10 w-10 text-white" />
                  </div>
                  <div className="absolute -top-2 -right-2 w-8 h-8 bg-[var(--accent)] rounded-full flex items-center justify-center text-sm font-bold">
                    {item.step}
                  </div>
                </div>
                <h3 className="text-xl font-semibold mb-3">{item.title}</h3>
                <p className="text-[var(--text-secondary)]">{item.desc}</p>
              </div>
            ))}
          </div>

          <div className="text-center mb-8">
            <button
              onClick={() => router.push("/csm-assessment")}
              className="btn-primary px-8 py-4 rounded-lg font-semibold text-lg inline-flex items-center"
            >
              Start Your Assessment
              <ArrowRight className="ml-2 h-5 w-5" />
            </button>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6 text-center">
            {[
              { icon: Shield, text: "Secure & Private" },
              { icon: Award, text: "94% Report Clearer Insights" },
              { icon: Brain, text: "Psychometrically Validated" },
              { icon: Lock, text: "Backed by Modern Psychology" },
            ].map((badge, index) => (
              <div key={index} className="card-gradient p-4 rounded-lg">
                <badge.icon className="h-8 w-8 text-[var(--accent)] mx-auto mb-2" />
                <p className="text-sm font-medium">{badge.text}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* What's Inside Section */}
      <section id="whats-inside" className="py-16 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12 section-header">
            <h2 className="text-4xl font-bold mb-6">
              A Comprehensive Guide to <span className="text-[var(--accent)]">Your Relationship</span>
            </h2>
          </div>

          <div className="space-y-12">
            {[
              {
                title: "In-Depth Profiles for Both Partners",
                subtitle: "Your Unique 'Couple's Dynamic' Analysis",
                desc: "Discover how your types create synergy or friction,with personalized tips.",
                image:
                  "https://images.pexels.com/photos/590016/pexels-photo-590016.jpeg?auto=compress&cs=tinysrgb&w=800",
                reverse: false,
              },
              {
                title: "Visual Analytics of Your Strengths & Growth Areas",
                subtitle: "Interactive Radar Charts and Comparisons",
                desc: "See at a glance where you complement each other and where growth opportunities lie.",
                image:
                  "https://images.pexels.com/photos/159888/pexels-photo-159888.jpeg?auto=compress&cs=tinysrgb&w=800",
                reverse: true,
              },
              {
                title: "A 10-Life-Area Deep Dive",
                subtitle: "From Career to Romance to Family Planning",
                desc: "Detailed analysis across every major life domain that matters to couples.",
                image:
                  "https://images.pexels.com/photos/842571/pexels-photo-842571.jpeg?auto=compress&cs=tinysrgb&w=800",
                reverse: false,
              },
              {
                title: "Communication & Conflict Resolution Toolkit",
                subtitle: "Practical Scripts and Strategies",
                desc: "Learn how to navigate disagreements using your unique communication styles.",
                image:
                  "https://images.pexels.com/photos/1080213/pexels-photo-1080213.jpeg?auto=compress&cs=tinysrgb&w=800",
                reverse: true,
              },
              {
                title: "Harmony vs. Autonomy Balance",
                subtitle: "Understanding Collaborative vs. Independent Motivations",
                desc: "Find the perfect balance between togetherness and individual space across all life areas.",
                image:
                  "https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg?auto=compress&cs=tinysrgb&w=800",
                reverse: false,
              },
            ].map((feature, index) => (
              <div
                key={index}
                className={`grid lg:grid-cols-2 gap-8 items-center ${feature.reverse ? "lg:grid-flow-col-dense" : ""}`}
              >
                <div className={`${feature.reverse ? "lg:col-start-2" : ""}`}>
                  <h3 className="text-2xl font-bold mb-2">{feature.title}</h3>
                  <h4 className="text-lg text-[var(--accent)] mb-4">{feature.subtitle}</h4>
                  <p className="text-[var(--text-secondary)] text-lg">{feature.desc}</p>
                </div>
                <div className={`${feature.reverse ? "lg:col-start-1" : ""}`}>
                  <div className="relative rounded-lg overflow-hidden">
                    <img
                      src={feature.image}
                      alt={`${feature.title} visualization`}
                      className="w-full h-64 object-cover"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-[var(--surface)]/40 to-transparent"></div>
                  </div>
                </div>
              </div>
            ))}
          </div>

          <div className="text-center mt-12">
            <button
              onClick={() => scrollToSection("buy-now")}
              className="btn-primary px-8 py-4 rounded-lg font-semibold text-lg inline-flex items-center"
            >
              Ready to see inside your report? Start Now
              <ArrowRight className="ml-2 h-5 w-5" />
            </button>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section id="faq" className="py-16 px-4 bg-[var(--surface-variant)]">
        <div className="container mx-auto max-w-4xl">
          <div className="text-center mb-12 section-header">
            <h2 className="text-4xl font-bold mb-6">
              Frequently Asked <span className="text-[var(--accent)]">Questions</span>
            </h2>
          </div>

          <div className="space-y-4 mb-12">
            {faqs.map((faq, index) => (
              <div key={index} className="card-gradient rounded-lg overflow-hidden">
                <button
                  onClick={() => toggleFAQ(index)}
                  className="w-full px-6 py-4 text-left flex justify-between items-center hover:bg-[var(--surface)]/20 transition-colors"
                >
                  <span className="font-semibold">{faq.question}</span>
                  {expandedFAQ === index ? (
                    <ChevronUp className="h-5 w-5 text-[var(--accent)]" />
                  ) : (
                    <ChevronDown className="h-5 w-5 text-[var(--accent)]" />
                  )}
                </button>
                {expandedFAQ === index && (
                  <div className="px-6 pb-4">
                    <p className="text-[var(--text-secondary)] leading-relaxed">{faq.answer}</p>
                  </div>
                )}
              </div>
            ))}
          </div>

          <div className="text-center card-gradient p-6 rounded-lg">
            <p className="text-lg mb-4">Got more questions?</p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <button
                onClick={() => router.push("/contact")}
                className="px-6 py-3 border border-[var(--border)] rounded-lg hover:bg-[var(--surface)] transition-colors"
              >
                Contact Us
              </button>
              <button
                onClick={() => router.push("/csm-assessment")}
                className="btn-primary px-6 py-3 rounded-lg font-semibold"
              >
                Start Your Free Assessment
              </button>
            </div>
          </div>
        </div>
      </section>

      {/* Buy Now Section */}
      <section id="buy-now" className="py-16 px-4">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-12 section-header">
            <h2 className="text-4xl font-bold mb-6">
              Transform Your Relationship <span className="text-[var(--accent)]">Today</span>
            </h2>
          </div>

          <div className="grid lg:grid-cols-3 gap-8 mb-12">
            {/* Pricing Card */}
            <div className="lg:col-span-2">
              <div className="card-gradient p-8 rounded-lg mb-8">
                <div className="flex items-center justify-between mb-6">
                  <div>
                    <h3 className="text-2xl font-bold">CSM Couple Insights Report</h3>
                    <p className="text-[var(--text-secondary)]">Complete relationship blueprint</p>
                  </div>
                  <div className="text-right">
                    <div className="text-3xl font-bold text-[var(--accent)]">$49</div>
                    <div className="text-sm text-[var(--text-secondary)]">One-time payment</div>
                  </div>
                </div>

                <div className="grid md:grid-cols-2 gap-4 mb-6">
                  {[
                    { icon: Clock, text: "Lifetime Dashboard Access" },
                    { icon: BarChart3, text: "Visual Analytics & Charts" },
                    { icon: Target, text: "10 Life Areas Analysis" },
                    { icon: MessageCircle, text: "Free Coaching Session" },
                    { icon: RefreshCw, text: "14-Day Money-Back Guarantee" },
                    { icon: Shield, text: "Secure & Private" },
                  ].map((feature, index) => (
                    <div key={index} className="flex items-center space-x-3">
                      <feature.icon className="h-5 w-5 text-[var(--accent)]" />
                      <span className="text-sm">{feature.text}</span>
                    </div>
                  ))}
                </div>

                <div className="bg-[var(--accent)]/10 p-4 rounded-lg mb-6">
                  <p className="text-[var(--accent)] font-semibold text-center">
                    Limited Offer: Free coach session available to first 500 sign-ups
                  </p>
                </div>

                <div className="flex flex-col sm:flex-row gap-4">
                  <button
                    onClick={handlePurchase}
                    className="btn-primary px-8 py-4 rounded-lg font-bold text-lg flex-1 flex items-center justify-center"
                  >
                    Buy Now for $49
                    <ArrowRight className="ml-2 h-5 w-5" />
                  </button>
                  <button
                    onClick={() => router.push("/csm-assessment")}
                    className="px-8 py-4 border border-[var(--border)] rounded-lg hover:bg-[var(--surface)] transition-colors flex items-center justify-center"
                  >
                    Start Free Assessment First
                  </button>
                </div>

                <div className="flex items-center justify-center space-x-4 mt-4 text-sm text-[var(--text-secondary)]">
                  <Shield className="h-4 w-4" />
                  <span>Secure checkout with Stripe/PayPal</span>
                </div>
              </div>
            </div>

            {/* Testimonials */}
            <div className="space-y-6">
              <div className="card-gradient p-6 rounded-lg">
                <div className="flex mb-3">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="h-4 w-4 text-yellow-400 fill-current" />
                  ))}
                </div>
                <p className="text-sm text-[var(--text-secondary)] mb-4">
                  {`"We're getting married next year, and this report gave us a roadmap for conversations we didn't even
                  know we needed to have. We feel more prepared than ever."`}
                </p>
                <div className="text-sm">
                  <span className="font-semibold">Sofia (The Mentor) & Leo (The Pioneer)</span>
                </div>
              </div>

              <div className="card-gradient p-6 rounded-lg">
                <div className="flex mb-3">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="h-4 w-4 text-yellow-400 fill-current" />
                  ))}
                </div>
                <p className="text-sm text-[var(--text-secondary)] mb-4">
                  {` "Seeing our financial styles laid out so clearly was an eye-opener. We created a joint plan that
                  honors both my need for security and her love for adventure."`}
                </p>
                <div className="text-sm">
                  <span className="font-semibold">David (The Analyst) & Maria (The Explorer)</span>
                </div>
              </div>
            </div>
          </div>

          <div className="text-center card-gradient p-6 rounded-lg">
            <p className="text-[var(--text-secondary)] mb-4">
              One-time payment of $49. Backed by our 14-day satisfaction guarantee,no questions asked.
            </p>
            <div className="flex items-center justify-center space-x-6 text-sm">
              <div className="flex items-center">
                <Shield className="h-4 w-4 mr-2 text-[var(--accent)]" />
                <span>SSL Encrypted</span>
              </div>
              <div className="flex items-center">
                <RefreshCw className="h-4 w-4 mr-2 text-[var(--accent)]" />
                <span>Money-Back Guarantee</span>
              </div>
              <div className="flex items-center">
                <Lock className="h-4 w-4 mr-2 text-[var(--accent)]" />
                <span>Privacy Protected</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="py-12 px-4 bg-[var(--surface-variant)] border-t border-[var(--border)]">
        <div className="container mx-auto max-w-6xl">
          <div className="grid md:grid-cols-4 gap-8">
            <div className="md:col-span-2">
              <div className="flex items-center space-x-2 mb-4">
                <Brain className="h-8 w-8 text-[var(--accent)]" />
                <span className="text-xl font-bold">CSM Insights</span>
              </div>
              <p className="text-[var(--text-secondary)] mb-4">
                Empowering couples with science-backed relationship insights through the Cognitive Spectrum Model.
              </p>
              <div className="flex space-x-4">
                <a
                  href="https://twitter.com"
                  className="text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors"
                >
                  Twitter
                </a>
                <a
                  href="https://facebook.com"
                  className="text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors"
                >
                  Facebook
                </a>
                <a
                  href="https://instagram.com"
                  className="text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors"
                >
                  Instagram
                </a>
              </div>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Legal</h4>
              <div className="space-y-2">
                <a
                  href="/privacy"
                  className="block text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors"
                >
                  Privacy Policy
                </a>
                <a
                  href="/terms"
                  className="block text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors"
                >
                  Terms of Service
                </a>
                <a
                  href="/refunds"
                  className="block text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors"
                >
                  Refund Policy
                </a>
              </div>
            </div>
            <div>
              <h4 className="font-semibold mb-4">Support</h4>
              <div className="space-y-2">
                <a
                  href="/contact"
                  className="block text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors"
                >
                  Contact Info
                </a>
                <a
                  href="/help"
                  className="block text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors"
                >
                  Help Center
                </a>
                <a
                  href="/csm-assessment"
                  className="block text-[var(--text-secondary)] hover:text-[var(--text-primary)] transition-colors"
                >
                  Free Assessment
                </a>
              </div>
            </div>
          </div>
          <div className="border-t border-[var(--border)] mt-8 pt-8 text-center text-[var(--text-secondary)]">
            <p>&copy; 2025 CSM Insights. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  );
}
