// 1. The Architect – C-L-O-S-H ok
// 2. The Engineer – C-L-O-S-A OK
// 3. The Navigator – C-L-O-F-H ok
// 4. The Pioneer – C-L-O-F-A ok
// 5. The Curator – C-L-I-S-H ok
// 6. The Analyst – C-L-I-S-A ok
// 7. The Mediator – C-L-I-F-H ok
// 8. The Maverick – C-L-I-F-A ok
// 9. The Steward – C-V-O-S-H ok
// 10. The Artisan – C-V-O-S-A ok
// 11. The Campaigner – C-V-O-F-H ok
// 12. The Adventurer – C-V-O-F-A ok
// 13. The Counselor – C-V-I-S-H ok
// 14. The Healer – C-V-I-S-A OK
// 15. The Peacemaker – C-V-I-F-H ok
// 16. The Empath – C-V-I-F-A ok
// 17. The Strategist – N-L-O-S-H ok
// 18. The Inventor – N-L-O-S-A ok
// 19. The Disruptor – N-L-O-F-H ok
// 20. The Revolutionary – N-L-O-F-A ok
// 21. The Academic – N-L-I-S-H ok
// 22. The Theorist – N-L-I-S-A ok
// 23. The Innovator – N-L-I-F-H ok
// 24. The Visionary – N-L-I-F-A ok
// 25. The Ambassador – N-V-O-S-H ok
// 26. The Artist – N-V-O-S-A ok
// 27. The Catalyst – N-V-O-F-H ok
// 28. The Wanderer – N-V-O-F-A OK
// 29. The Mentor – N-V-I-S-H ok
// 30. The Sage – N-V-I-S-A ok
// 31. The Unifier – N-V-I-F-H ok
// 32. The Mystic – N-V-I-F-A ok
