"use client";
import * as React from "react";
import Box from "@mui/material/Box";
import Stack from "@mui/material/Stack";
import FormControlLabel from "@mui/material/FormControlLabel";
import Checkbox from "@mui/material/Checkbox";
import { RadarChart } from "@mui/x-charts/RadarChart";

// --- Data & Settings ---
// 👇 Logic moved into the legend's onClick handler
const getCommonSettings = (setHighlightedSeries) => ({
  height: 300,
  margin: { top: 30, right: 10, bottom: 10, left: 10 },
  radar: {
    max: 100,
    metrics: ["(I)", "(S)", "(H)", "(V)", "(N)"],
  },
  legend: {
    // ✅ This is the correct way to handle legend clicks
    onClick: (event, d) => setHighlightedSeries((prev) => (prev === d.label ? null : d.label)),
  },
});

const lisaGrades = {
  label: "You",
  data: [51, 57, 56, 51, 52],
  color: "#6366f1",
};

const bartGrades = {
  label: "Your Partner",
  data: [75, 69, 52, 75, 55],
  color: "#f43f5e",
};

// --- Component ---
export default function DemoRadarAxisHighlight() {
  const [hideMark, setHideMark] = React.useState(false);
  const [fillSeries, setFillSeries] = React.useState({
    You: true,
    "Your Partner": false,
  });
  const [highlightedSeries, setHighlightedSeries] = React.useState(null);

  // 👇 commonSettings is now generated by a function to access the state setter
  const commonSettings = React.useMemo(() => getCommonSettings(setHighlightedSeries), []);

  const getSeries = () => {
    return [lisaGrades, bartGrades].map((series) => ({
      ...series,
      hideMark,
      area: fillSeries[series.label] ? { opacity: 0.3 } : false,
      highlighted: highlightedSeries === series.label,
    }));
  };

  const handleFillChange = (event) => {
    setFillSeries((prev) => ({
      ...prev,
      [event.target.name]: event.target.checked,
    }));
  };

  return (
    <Box sx={{ width: "100%" }}>
      <Stack sx={{ width: "100%", mb: 2 }} direction="row" flexWrap="wrap" gap={2}>
        {/* Controls... */}
        <FormControlLabel
          checked={!hideMark}
          control={<Checkbox onChange={(event) => setHideMark(!event.target.checked)} />}
          label="With Mark"
          labelPlacement="end"
        />
        <FormControlLabel
          label='Fill "You"'
          control={
            <Checkbox
              name="You"
              checked={fillSeries.You}
              onChange={handleFillChange}
              sx={{ color: lisaGrades.color, "&.Mui-checked": { color: lisaGrades.color } }}
            />
          }
        />
        <FormControlLabel
          label='Fill "Your Partner"'
          control={
            <Checkbox
              name="Your Partner"
              checked={fillSeries["Your Partner"]}
              onChange={handleFillChange}
              sx={{ color: bartGrades.color, "&.Mui-checked": { color: bartGrades.color } }}
            />
          }
        />
      </Stack>

      <Stack sx={{ width: "100%" }} direction="row" flexWrap="wrap" justifyContent="space-around">
        <Box sx={{ width: "100%", maxWidth: 450 }}>
          <div className="radar-dark">
            <RadarChart
              {...commonSettings}
              series={getSeries()}
              // ⛔️ The incorrect onItemClick prop has been removed from here.
              slotProps={{
                tooltip: {
                  disablePortal: true,
                  sx: {
                    "& .MuiChartsTooltip-paper": {
                      backgroundColor: "#1f2937",
                      color: "#ffffff",
                      border: "1px solid #374151",
                    },
                  },
                },
              }}
              sx={{
                "& .MuiChartsAxis-root text": { fill: "#fff" },
                "& .MuiChartsAxisHighlight-root text": { fill: "#fff" },
                "& .MuiChartsAxis-line": { stroke: "#fff" },
                "& .MuiChartsGrid-line": { stroke: "#fff" },
                "& svg line[stroke-dasharray]": {
                  stroke: "#fff",
                  strokeDasharray: "4 4",
                },
                "& .MuiChartsCursor-root line": {
                  stroke: "#fff",
                  strokeDasharray: "4 4",
                },
                "& .MuiChartsLegend-label": {
                  fill: "#fff",
                  color: "#fff",
                },
              }}
            />
          </div>
        </Box>
      </Stack>
    </Box>
  );
}
